version: "3.8"
services: 
  db:
    image: postgres:11.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/log:/var/log
    command: postgres -c shared_buffers=256MB
  discordbot:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    depends_on: 
      - db